# Generated by Django 3.2 on 2022-06-18 03:25

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('imagen', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dyg8vlnnz/image/upload/v1655522501/user_icon_149851_lxy1jt.png', max_length=255, verbose_name='image')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='Cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cochera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='descripcion', max_length=10000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen1', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('imagen2', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('imagen3', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('space', models.IntegerField(default=1)),
                ('country', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=200)),
                ('long', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.RESTRICT, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('horaInicio', models.TimeField(null=True)),
                ('horaFin', models.TimeField(null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.cliente')),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.cochera')),
            ],
        ),
    ]
