# Generated by Django 3.2 on 2022-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cochera',
            name='description',
            field=models.TextField(default='descripcion', max_length=10000),
        ),
    ]
