# Generated by Django 3.2 on 2022-06-20 21:35

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cochera',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='cliente',
            field=models.ForeignKey(blank=True, default='Null', on_delete=django.db.models.deletion.RESTRICT, to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='description',
            field=models.TextField(blank=True, default='descripcion', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='imagen1',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='imagen2',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='imagen3',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='long',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cochera',
            name='space',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
