# Generated by Django 3.2 on 2022-06-17 03:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cochera_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, null=True, verbose_name='image'),
        ),
    ]
