# Generated by Django 3.2 on 2022-06-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cliente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='horaFin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horaInicio',
            field=models.TimeField(null=True),
        ),
    ]
